### ISSUE TITLE
Restrict all Zip codes to format with only five numbers

### ISSUE THREAD

**Issue by markrmessmore** [markrmessmore/childcare-connection#19]
Like it says, some of the Zip codes (particularly on the Employment/School/Training section) are allowing more than five characters.

**Comment by phr-nk** [comment]
I could help with this.

**Comment by markrmessmore** [comment]
> I could help with this.

Excellent. Give me about 5 minutes from when this is posted to update the readme with the login info.

**Comment by markrmessmore** [comment]
@phr-nk I realized my firebase DEV environment settings were accidentally in .gitignore. I've fixed that and they are available now. May want to pull to update.
