### ISSUE TITLE
Move to FontAwesome

### ISSUE THREAD

**Issue by markrmessmore** [markrmessmore/childcare-connection#23]
I would like to move from the material design icon library to font awesome. Please change the library and update all fonts across the app.

**Comment by rene-ph** [comment]
@markrmessmore can I own this feature? thanks!

**Comment by rene-ph** [comment]
@markrmessmore This not regarding this task but I think is good to know if this has happened to you. 
When I tried to do npm run serve I couldn't run the app and it threw an error related to core-js
and the way I fixed it was to change the first line in the babel.config.js with this code:
 presets: [ [ "@vue/app", { useBuiltIns: "entry" } ] ].

**Comment by markrmessmore** [comment]
Thanks so much @rene-ph I'll take a look at that. I haven't touched this code for over a year so several libraries are needing updates. Thanks for the insight.
